import jsPDF from 'jspdf';
import { AgentTrendSummary, AgentDailyTrend } from '@/hooks/useAgentPerformanceTrends';
import { format } from 'date-fns';

interface AgentReportData {
  summary: AgentTrendSummary;
  dailyTrends: AgentDailyTrend[];
  days: number;
  generatedAt: Date;
  generatedBy?: string;
}

export const generateAgentPerformancePDF = async (data: AgentReportData): Promise<void> => {
  const { summary, dailyTrends, days, generatedAt, generatedBy } = data;
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPos = 20;

  // Helper functions
  const addText = (text: string, x: number, y: number, options?: { fontSize?: number; fontStyle?: 'normal' | 'bold'; color?: [number, number, number] }) => {
    const { fontSize = 12, fontStyle = 'normal', color = [0, 0, 0] } = options || {};
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', fontStyle);
    doc.setTextColor(...color);
    doc.text(text, x, y);
  };

  const addLine = (y: number) => {
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageWidth - margin, y);
  };

  const checkNewPage = (requiredSpace: number) => {
    if (yPos + requiredSpace > doc.internal.pageSize.getHeight() - 20) {
      doc.addPage();
      yPos = 20;
    }
  };

  // Header
  addText('Agent Performance Report', margin, yPos, { fontSize: 24, fontStyle: 'bold', color: [41, 98, 255] });
  yPos += 12;
  addText(summary.agentName, margin, yPos, { fontSize: 16, fontStyle: 'bold' });
  yPos += 8;
  addText(`${days}-Day Performance Review`, margin, yPos, { fontSize: 12, color: [100, 100, 100] });
  yPos += 15;
  addLine(yPos);
  yPos += 15;

  // Report metadata
  addText('Report Details', margin, yPos, { fontSize: 14, fontStyle: 'bold' });
  yPos += 8;
  addText(`Generated: ${format(generatedAt, 'MMMM d, yyyy \'at\' h:mm a')}`, margin, yPos, { fontSize: 10, color: [100, 100, 100] });
  yPos += 5;
  if (generatedBy) {
    addText(`Generated by: ${generatedBy}`, margin, yPos, { fontSize: 10, color: [100, 100, 100] });
    yPos += 5;
  }
  addText(`Period: Last ${days} days`, margin, yPos, { fontSize: 10, color: [100, 100, 100] });
  yPos += 15;

  // Summary Section
  addText('Performance Summary', margin, yPos, { fontSize: 16, fontStyle: 'bold' });
  yPos += 10;

  // Summary cards in a grid
  const cardWidth = (pageWidth - margin * 2 - 10) / 2;
  const cardHeight = 25;
  
  const summaryItems = [
    { label: 'Total Calls', value: summary.totalCalls.toLocaleString() },
    { label: 'Interested Leads', value: summary.totalInterested.toLocaleString() },
    { label: 'Leads Generated', value: summary.totalLeads.toLocaleString() },
    { label: 'Avg Conversion Rate', value: `${summary.avgConversionRate}%` },
    { label: 'Avg Calls/Day', value: summary.avgCallsPerDay.toLocaleString() },
    { label: 'Best Day', value: `${summary.bestDay} (${summary.bestDayCalls} calls)` },
  ];

  summaryItems.forEach((item, index) => {
    const col = index % 2;
    const row = Math.floor(index / 2);
    const x = margin + col * (cardWidth + 10);
    const y = yPos + row * (cardHeight + 5);

    // Card background
    doc.setFillColor(248, 249, 250);
    doc.roundedRect(x, y, cardWidth, cardHeight, 3, 3, 'F');

    // Card content
    addText(item.value, x + 8, y + 10, { fontSize: 14, fontStyle: 'bold' });
    addText(item.label, x + 8, y + 18, { fontSize: 9, color: [100, 100, 100] });
  });

  yPos += Math.ceil(summaryItems.length / 2) * (cardHeight + 5) + 15;

  // Trend indicator
  const trendText = summary.trend === 'up' 
    ? `↑ ${summary.trendPercentage}% improvement vs prior period`
    : summary.trend === 'down'
    ? `↓ ${summary.trendPercentage}% decrease vs prior period`
    : `→ Stable performance vs prior period`;
  
  const trendColor: [number, number, number] = summary.trend === 'up' 
    ? [34, 197, 94] 
    : summary.trend === 'down' 
    ? [239, 68, 68] 
    : [100, 100, 100];

  addText(trendText, margin, yPos, { fontSize: 11, fontStyle: 'bold', color: trendColor });
  yPos += 20;

  // Daily Breakdown Table
  checkNewPage(60);
  addText('Daily Performance Breakdown', margin, yPos, { fontSize: 16, fontStyle: 'bold' });
  yPos += 10;

  // Table header
  const colWidths = [30, 22, 28, 32, 28, 22, 22];
  const headers = ['Date', 'Calls', 'Interested', 'Not Interested', 'No Answer', 'Leads', 'Conv %'];
  
  doc.setFillColor(41, 98, 255);
  doc.rect(margin, yPos, pageWidth - margin * 2, 8, 'F');
  
  let xPos = margin + 3;
  headers.forEach((header, i) => {
    addText(header, xPos, yPos + 5.5, { fontSize: 8, fontStyle: 'bold', color: [255, 255, 255] });
    xPos += colWidths[i];
  });
  yPos += 10;

  // Table rows
  const reversedTrends = [...dailyTrends].reverse();
  reversedTrends.forEach((day, index) => {
    checkNewPage(8);
    
    // Alternating row background
    if (index % 2 === 0) {
      doc.setFillColor(248, 249, 250);
      doc.rect(margin, yPos - 2, pageWidth - margin * 2, 7, 'F');
    }

    xPos = margin + 3;
    const values = [
      day.displayDate,
      day.totalCalls.toString(),
      day.interested.toString(),
      day.notInterested.toString(),
      day.notAnswered.toString(),
      day.leadsGenerated.toString(),
      `${day.conversionRate}%`,
    ];

    values.forEach((value, i) => {
      let color: [number, number, number] = [0, 0, 0];
      if (i === 2) color = [34, 197, 94]; // Interested - green
      if (i === 3) color = [239, 68, 68]; // Not interested - red
      if (i === 4) color = [100, 100, 100]; // No answer - gray
      if (i === 5) color = [234, 179, 8]; // Leads - yellow/warning
      
      addText(value, xPos, yPos + 3, { fontSize: 8, color });
      xPos += colWidths[i];
    });
    yPos += 7;
  });

  yPos += 10;

  // Footer
  checkNewPage(20);
  addLine(yPos);
  yPos += 8;
  addText('This report was automatically generated by the Sales Performance System.', margin, yPos, { fontSize: 8, color: [150, 150, 150] });
  yPos += 4;
  addText('For questions or clarifications, please contact your supervisor.', margin, yPos, { fontSize: 8, color: [150, 150, 150] });

  // Save the PDF
  const fileName = `${summary.agentName.replace(/\s+/g, '_')}_Performance_Report_${format(generatedAt, 'yyyy-MM-dd')}.pdf`;
  doc.save(fileName);
};
